if (CPACK_BUILD_CONFIG MATCHES Release)
	set(_CONFIG "")
elseif (CPACK_BUILD_CONFIG MATCHES Debug)
	set(_CONFIG "dbg-")
endif ()

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${_CONFIG}${CPACK_COMPILER}-x86_64-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")